# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[default]
account = "maailwu-nz88441"
user = "edadou"
password = "Brugn0n666&"
role = "HOL_ROLE"
warehouse = "HOL_WH"
database = "TRAINING_DB"
schema = "TRAINING"
